version: '3'

services:

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=PassWord
      - MYSQL_DATABASE=login_system
      - MYSQL_USER=user
      - MYSQL_PASSWORD=A13781378a
    ports:
      - 3306:3306
    volumes:
      - $PWD/data:/var/lib/mysql:rw


  login_system:
    #build: .
    image: registry.vaslapp.com/docker/melika/login-system:latest
    restart: on-failure
    depends_on:
      mysql:
        condition: service_started
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=user
      - DATABASE_PASSWORD=A13781378a
      - DATABASE_NAME=login_system
      - DATABASE_PORT=3306